package server;
// Generated 23.11.2014 21:24:17 by Hibernate Tools 3.2.1.GA



/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private int idoforder;
     private int idofbook;
     private int idofuser;

    public Orders() {
    }

    public Orders(int idoforder, int idofbook, int idofuser) {
       this.idoforder = idoforder;
       this.idofbook = idofbook;
       this.idofuser = idofuser;
    }
   
    public int getIdoforder() {
        return this.idoforder;
    }
    
    public void setIdoforder(int idoforder) {
        this.idoforder = idoforder;
    }
    public int getIdofbook() {
        return this.idofbook;
    }
    
    public void setIdofbook(int idofbook) {
        this.idofbook = idofbook;
    }
    public int getIdofuser() {
        return this.idofuser;
    }
    
    public void setIdofuser(int idofuser) {
        this.idofuser = idofuser;
    }



}


