package server;
// Generated 23.11.2014 21:24:17 by Hibernate Tools 3.2.1.GA



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int idofuser;
     private String role;
     private String name;
     private String password;

    public Users() {
    }

	
    public Users(int idofuser) {
        this.idofuser = idofuser;
    }
    public Users(int idofuser, String role, String name, String password) {
       this.idofuser = idofuser;
       this.role = role;
       this.name = name;
       this.password = password;
    }
   
    public int getIdofuser() {
        return this.idofuser;
    }
    
    public void setIdofuser(int idofuser) {
        this.idofuser = idofuser;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

}


